/**
 * Generate OpenAPI 3.0 spec from introspected model metadata.
 */
function generateOpenAPISpec(models, options = {}) {
  const basePath = options.basePath || "/api";
  const title = options.title || "REST Router API";
  const version = options.version || "1.0.0";

  const spec = {
    openapi: "3.0.3",
    info: {
      title,
      version,
      description: "Auto-generated by db-model-router CLI",
    },
    paths: {},
    components: { schemas: {} },
  };

  for (const m of models) {
    const tag = m.table;
    const pk = m.primary_key;
    const schemaName = capitalize(m.table);

    // Build schema from modelStructure
    const properties = {};
    const required = [];
    // Add PK
    properties[pk] = { type: "integer", description: "Primary key" };
    for (const [col, rule] of Object.entries(m.structure)) {
      const parsed = parseRule(rule);
      properties[col] = { type: parsed.type };
      if (parsed.required) required.push(col);
    }
    spec.components.schemas[schemaName] = {
      type: "object",
      properties,
      ...(required.length > 0 ? { required } : {}),
    };

    const ref = { $ref: `#/components/schemas/${schemaName}` };
    const prefix = `${basePath}/${m.table}`;

    // GET / — list
    spec.paths[`${prefix}/`] = {
      get: {
        tags: [tag],
        summary: `List ${m.table}`,
        parameters: [
          {
            name: "page",
            in: "query",
            schema: { type: "integer", default: 0 },
          },
          {
            name: "size",
            in: "query",
            schema: { type: "integer", default: 30 },
          },
          { name: "sort", in: "query", schema: { type: "string" } },
          {
            name: "select_columns",
            in: "query",
            schema: { type: "string" },
            description: "Comma-separated column names",
          },
          {
            name: "output_content_type",
            in: "query",
            schema: { type: "string", enum: ["json", "csv", "xml"] },
          },
        ],
        responses: {
          200: {
            description: "Success",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    data: { type: "array", items: ref },
                    count: { type: "integer" },
                  },
                },
              },
            },
          },
        },
      },
      post: {
        tags: [tag],
        summary: `Bulk insert ${m.table}`,
        requestBody: {
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { data: { type: "array", items: ref } },
              },
            },
          },
        },
        responses: { 200: { description: "Success" } },
      },
      put: {
        tags: [tag],
        summary: `Bulk update ${m.table}`,
        requestBody: {
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: { data: { type: "array", items: ref } },
              },
            },
          },
        },
        responses: { 200: { description: "Success" } },
      },
      delete: {
        tags: [tag],
        summary: `Bulk delete ${m.table}`,
        requestBody: {
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  data: { type: "array", items: { type: "object" } },
                },
              },
            },
          },
        },
        responses: { 200: { description: "Success" } },
      },
    };

    // GET /:id, POST /:id, PUT /:id, PATCH /:id, DELETE /:id
    spec.paths[`${prefix}/{${pk}}`] = {
      get: {
        tags: [tag],
        summary: `Get ${m.table} by ${pk}`,
        parameters: [
          { name: pk, in: "path", required: true, schema: { type: "string" } },
          { name: "select_columns", in: "query", schema: { type: "string" } },
          {
            name: "output_content_type",
            in: "query",
            schema: { type: "string", enum: ["json", "csv", "xml"] },
          },
        ],
        responses: {
          200: {
            description: "Success",
            content: { "application/json": { schema: ref } },
          },
          404: { description: "Not Found" },
        },
      },
      post: {
        tags: [tag],
        summary: `Insert a ${m.table}`,
        parameters: [
          { name: pk, in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: { content: { "application/json": { schema: ref } } },
        responses: {
          200: {
            description: "Created",
            content: { "application/json": { schema: ref } },
          },
        },
      },
      put: {
        tags: [tag],
        summary: `Update a ${m.table}`,
        parameters: [
          { name: pk, in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: { content: { "application/json": { schema: ref } } },
        responses: {
          200: {
            description: "Updated",
            content: { "application/json": { schema: ref } },
          },
          404: { description: "Not Found" },
        },
      },
      patch: {
        tags: [tag],
        summary: `Partial update a ${m.table}`,
        parameters: [
          { name: pk, in: "path", required: true, schema: { type: "string" } },
        ],
        requestBody: {
          content: { "application/json": { schema: { type: "object" } } },
        },
        responses: {
          200: {
            description: "Updated",
            content: { "application/json": { schema: ref } },
          },
          404: { description: "Not Found" },
        },
      },
      delete: {
        tags: [tag],
        summary: `Delete a ${m.table}`,
        parameters: [
          { name: pk, in: "path", required: true, schema: { type: "string" } },
        ],
        responses: {
          200: { description: "Deleted" },
          404: { description: "Not Found" },
        },
      },
    };
  }

  return spec;
}

function parseRule(rule) {
  const parts = rule.split("|");
  const isRequired = parts.includes("required");
  let type = "string";
  for (const p of parts) {
    if (p === "integer") type = "integer";
    else if (p === "numeric") type = "number";
    else if (p === "object") type = "object";
    else if (p === "string") type = "string";
  }
  return { type, required: isRequired };
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

module.exports = { generateOpenAPISpec };
