/**
 * Oracle DDL → PostgreSQL DDL Translation
 * Used by the migration runner to convert Oracle-specific DDL to PostgreSQL equivalents.
 */

function translateDDL(sql) {
  if (!sql || typeof sql !== 'string') return sql;

  // NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY → SERIAL (or BIGSERIAL)
  sql = sql.replace(/\bNUMBER\s+GENERATED\s+(?:BY\s+DEFAULT\s+ON\s+NULL\s+|ALWAYS\s+)AS\s+IDENTITY\b/gi, 'BIGSERIAL');

  // NUMBER(1) → SMALLINT (used for booleans)
  sql = sql.replace(/\bNUMBER\s*\(\s*1\s*\)/gi, 'SMALLINT');

  // NUMBER(p,s) → NUMERIC(p,s)
  sql = sql.replace(/\bNUMBER\s*\(\s*(\d+)\s*,\s*(\d+)\s*\)/gi, 'NUMERIC($1,$2)');

  // NUMBER(p) → NUMERIC(p)
  sql = sql.replace(/\bNUMBER\s*\(\s*(\d+)\s*\)/gi, 'NUMERIC($1)');

  // NUMBER → BIGINT (bare NUMBER without precision)
  sql = sql.replace(/\bNUMBER\b(?!\s*\()/gi, 'BIGINT');

  // VARCHAR2(n) → VARCHAR(n)
  sql = sql.replace(/\bVARCHAR2\s*\(/gi, 'VARCHAR(');

  // CLOB → TEXT
  sql = sql.replace(/\bCLOB\b/gi, 'TEXT');

  // BLOB → BYTEA
  sql = sql.replace(/\bBLOB\b/gi, 'BYTEA');

  // SYSTIMESTAMP → NOW()
  sql = sql.replace(/\bSYSTIMESTAMP\b/gi, 'NOW()');

  // SYSDATE → NOW()
  sql = sql.replace(/\bSYSDATE\b/gi, 'NOW()');

  // Oracle trigger syntax → PostgreSQL trigger function + trigger
  if (/\bCREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\b/i.test(sql)) {
    sql = translateTrigger(sql);
  }

  return sql;
}

function translateTrigger(sql) {
  // Parse Oracle trigger: CREATE [OR REPLACE] TRIGGER name AFTER INSERT|UPDATE ON table FOR EACH ROW BEGIN ... END;
  const match = sql.match(
    /CREATE\s+(?:OR\s+REPLACE\s+)?TRIGGER\s+(\w+)\s+(BEFORE|AFTER)\s+(INSERT|UPDATE|DELETE)\s+ON\s+(\w+)\s+FOR\s+EACH\s+ROW\s+BEGIN\s+([\s\S]+?)\s*END;?/i
  );
  if (!match) return sql;

  const [, triggerName, timing, event, tableName, body] = match;

  // Convert :NEW.col → NEW.col and :OLD.col → OLD.col
  let pgBody = body.replace(/:NEW\./gi, 'NEW.').replace(/:OLD\./gi, 'OLD.');

  // Convert Oracle DDL types in the body
  pgBody = pgBody.replace(/\bVARCHAR2\s*\(/gi, 'VARCHAR(');
  pgBody = pgBody.replace(/\bNUMBER\b/gi, 'BIGINT');
  pgBody = pgBody.replace(/\bCLOB\b/gi, 'TEXT');

  const funcName = triggerName + '_func';

  return `CREATE OR REPLACE FUNCTION ${funcName}() RETURNS TRIGGER AS $$\nBEGIN\n  ${pgBody.trim()}\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;\n\nCREATE TRIGGER ${triggerName}\n${timing} ${event} ON ${tableName}\nFOR EACH ROW\nEXECUTE FUNCTION ${funcName}()`;
}

module.exports = { translateDDL };
